In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
np.array([1, 2, 3, 3, 4, 5, 42, 312, 321, 312])

array([  1,   2,   3,   3,   4,   5,  42, 312, 321, 312])

In [5]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, 312, 321, 312])
type(arr), arr

(numpy.ndarray, array([  1,   2,   3,   3,   4,   5,  42, 312, 321, 312]))

In [6]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, 312, 321, 312])
print(type(arr), arr, arr.dtype)

<class 'numpy.ndarray'> [  1   2   3   3   4   5  42 312 321 312] int64


In [7]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, 312, 321, 312])
print(arr, type(arr),  arr.dtype)

[  1   2   3   3   4   5  42 312 321 312] <class 'numpy.ndarray'> int64


In [8]:
arr = np.array([1, 2, 3, 3, 4.321 , 5, 42, 312, 321, 312])
print(arr, type(arr),  arr.dtype)

[  1.      2.      3.      3.      4.321   5.     42.    312.    321.
 312.   ] <class 'numpy.ndarray'> float64


In [9]:
arr = np.array([1, 2, 3, 3, 4.321 , 5, 42, 312, 321, 312, "hello"])
print(arr, type(arr),  arr.dtype)

['1' '2' '3' '3' '4.321' '5' '42' '312' '321' '312' 'hello'] <class 'numpy.ndarray'> <U32


In [10]:
arr = np.array([1, 2, 3, 3, 4.321 , 5, 42, 312, 321, 312, "hello", [320, 3210]])
print(arr, type(arr),  arr.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (12,) + inhomogeneous part.

In [11]:
arr = np.array([ [ 321, 312], [320, 3210]])
print(arr, type(arr),  arr.dtype)

[[ 321  312]
 [ 320 3210]] <class 'numpy.ndarray'> int64


In [13]:
arr = np.array([ [ 321, 312, 524], [320, 3210, 312]])
print(arr, type(arr),  arr.dtype)

[[ 321  312  524]
 [ 320 3210  312]] <class 'numpy.ndarray'> int64


# Data type

In [15]:
arr = np.array([1, 2, 3, 3, 4, 5, 42], dtype=np.int8)
print(arr, type(arr),  arr.dtype)

[ 1  2  3  3  4  5 42] <class 'numpy.ndarray'> int8


In [16]:
for i in range(20):
    print("i=", i,  " : ", bin(i))


i= 0  :  0b0
i= 1  :  0b1
i= 2  :  0b10
i= 3  :  0b11
i= 4  :  0b100
i= 5  :  0b101
i= 6  :  0b110
i= 7  :  0b111
i= 8  :  0b1000
i= 9  :  0b1001
i= 10  :  0b1010
i= 11  :  0b1011
i= 12  :  0b1100
i= 13  :  0b1101
i= 14  :  0b1110
i= 15  :  0b1111
i= 16  :  0b10000
i= 17  :  0b10001
i= 18  :  0b10010
i= 19  :  0b10011


In [17]:
2 ** 8 - 1

255

# uint8 - este de la 0..255

In [19]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, 255], dtype=np.uint8)
print(arr, type(arr),  arr.dtype)

[  1   2   3   3   4   5  42 255] <class 'numpy.ndarray'> uint8


# int8 - este de la -128 la 127

In [21]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, 127], dtype=np.int8)
print(arr, type(arr),  arr.dtype)

[  1   2   3   3   4   5  42 127] <class 'numpy.ndarray'> int8


In [23]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, -128], dtype=np.int8)
print(arr, type(arr),  arr.dtype)

[   1    2    3    3    4    5   42 -128] <class 'numpy.ndarray'> int8


# Mathematical operations

In [24]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, -128])
arr

array([   1,    2,    3,    3,    4,    5,   42, -128])

In [25]:
arr  +  2

array([   3,    4,    5,    5,    6,    7,   44, -126])

In [26]:
arr  + arr

array([   2,    4,    6,    6,    8,   10,   84, -256])

In [27]:
arr  * 2

array([   2,    4,    6,    6,    8,   10,   84, -256])

In [28]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, -128])
arr > 5


array([False, False, False, False, False, False,  True, False])

In [29]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, -128])
arr > 0

array([ True,  True,  True,  True,  True,  True,  True, False])

In [30]:
arr = np.array([1, 2, 3, 3, 4, 5, 42, -128])
arr[arr > 0]

array([ 1,  2,  3,  3,  4,  5, 42])

#  Random Number Generation

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.random.randint(1, 10)

9

In [34]:
np.random.randint(1, 10, 5)

array([1, 1, 4, 2, 7])

In [35]:
np.random.randint(1, 10, 5)

array([4, 9, 7, 7, 6])

In [36]:
np.random.randint(1, 10, (3, 2))

array([[9, 1],
       [5, 8],
       [1, 1]])

In [37]:
np.random.randint(1, 10, (2, 3))

array([[4, 2, 3],
       [6, 1, 8]])